### PR TITLE
clarifying change to nats-server for JetStream

### PR DESCRIPTION
**Pull request by gcolliso**
in response to a question about JetStream support on Slack #general channel

### CODE REVIEW

**Comment by ripienaar** [comment]
What do you think we should do with this repo? I moved all things out of it - can migrate the few remaining issues. 

We can then archive it or delete it or leave it as is?

**Comment by gcolliso** [comment]
I'm not sure - Maybe see what @derekcollison or @ColinSullivan1 think.

**Comment by derekcollison** [comment]
Let's migrate and archive.

**Review by ripienaar — APPROVED** [review]
LGTM, lets merge and I'll work to retire this

**Pull request merged**
