### PR TITLE
Add complete implementation of `JetStream Work Queue` example

### PR DESCRIPTION
**Pull request by masudur-rahman**
Signed-off-by: Masudur Rahman <masudjuly02@gmail.com>

### CODE REVIEW

**Comment by ripienaar** [comment]
hmm, sorry, my bad - I somehow missed we already have worker.go which is what you were asking.  Maybe rename this to worker-full.go, you dont need a new PR just rename and do another push on the same branch.

**Comment by masudur-rahman** [comment]
okay

**Comment by masudur-rahman** [comment]
As I need a separate `main.go` for this example, that's why I moved it to a separate directory.

**Comment by ripienaar** [comment]
perfect thanks

**Pull request merged**
